Improve SQLite compatibility
wp-cli/core-command pull request #243
Opened 2023-10-23 16:28 UTC by swissspidy

Fixes #242

2023-10-23 20:22 UTC, danielbachhuber reviewed
Can we make sure there are GitHub issues open for the TODO comments? They will probably be forgotten otherwise.

Also, I'm a little bit wary of all of the `@require-mysql` statements because it means we're skipping the tests for SQLite. I don't think it necessarily blocks this, but we might want to track it in some way.

2023-10-23 20:25 UTC, danielbachhuber commented
> Also, I'm a little bit wary of all of the `@require-mysql` statements because it means we're skipping the tests for SQLite. I don't think it necessarily blocks this, but we might want to track it in some way.

Another potential way to solve this: create a custom Matrix for the SQLite tests, and only run SQLite for WordPress 6.0 and higher. I think this would be my recommended approach.

2023-10-23 20:50 UTC, swissspidy commented
> Another potential way to solve this: create a custom Matrix for the SQLite tests, and only run SQLite for WordPress 6.0 and higher. 

This is already the case, actually. What's happening here is that some individual scenarios downgrade to WordPress 4.0 and then upgrade to the latest version.

> Can we make sure there are GitHub issues open for the TODO comments? They will probably be forgotten otherwise.

Totally. The only TODO that doesn't have one yet is the one about `CUSTOM_USER_TABLE`. I'm not yet sure whether it's an issue with the command or the SQLite plugin.

2023-11-01 18:29 UTC, swissspidy commented
@danielbachhuber WDYT about the reworded comments?

2023-11-01 23:19 UTC, danielbachhuber requested changes

2023-11-01 23:19 UTC, danielbachhuber commented on features/core-install.feature
> +  # # This test downgrades to an older WordPress version, but the SQLite plugin requires 6.0+
```suggestion
  # This test downgrades to an older WordPress version, but the SQLite plugin requires 6.0+
```

2023-11-01 23:19 UTC, danielbachhuber commented on features/core-install.feature
> +  # TODO: Requires investigation for SQLite support.
Can we include a link to the relevant GitHub issue too?

2023-11-01 23:19 UTC, danielbachhuber commented on features/core-install.feature
> +  # TODO: Requires investigation for SQLite support.
Can we include a link to the relevant GitHub issue too?

2023-11-01 23:19 UTC, danielbachhuber commented on features/core-check-update.feature
> +  # # This test downgrades to an older WordPress version, but the SQLite plugin requires 6.0+
```suggestion
  # This test downgrades to an older WordPress version, but the SQLite plugin requires 6.0+
```

2023-11-01 23:19 UTC, danielbachhuber commented on features/core-update-db.feature
> +  # # This test downgrades to an older WordPress version, but the SQLite plugin requires 6.0+
```suggestion
  # This test downgrades to an older WordPress version, but the SQLite plugin requires 6.0+
```

There are a lot of these...

2023-11-04 12:49 UTC, danielbachhuber approved these changes

2023-11-04 12:49 UTC, merged